version: '3.8'
services:
    service_1:
        container_name: service_1
        image: callumdunn810/service_1
        build: ./service_1
        deploy:
            replicas: 5
        protocol: tcp
        ports: 
        - published: 5000
          target: 5000
        environment:
          DATABASE_URI: ${DATABASE_URI}
    2_skill:
        container_name: service_2_skill
        image: callumdunn810/service_2_skill
        build: ./service_2_skill
        deploy:
            replicas: 5
        protocol: tcp
        ports:
        - published: 5001
        target: 5001
        depends on:
        - 'server'
    3_alliance:
        container_name: service_3_alliance
        image: callumdunn810/service_3_alliance
        build: ./service_3_alliance
        deploy:
            replicas: 5
        protocol: tcp
        ports:
        - published: 5002
        target: 5002
        depends on:
        - 'server'
    4_race:
        container_name: service_4_race
        image: callumdunn810/service_4_race
        build: ./service_4_racedeploy:
            replicas: 3
        protocol: tcp
        ports:
        - published: 5003
        target: 5003
        depends on:
        - 'server'
