version: '3.8'
services:
    service1:
        container_name: service1
        image: callumdunn810/service1
        build: ./service1
        ports: 
        - published: 5000
          target: 5000
        environment:
          DATABASE_URI: ${DATABASE_URI}
    service2:
        container_name: service2-skill
        image: callumdunn810/service1-skill
        build: ./service2-skill
    service3:
        container_name: service3-alliance
        image: callumdunn810/service3-alliance
        build: ./service3-alliance
    service4:
        container_name: service4-race
        image: callumdunn810/service4-race
        build: ./service4-race